# Generated by Django 5.0.1 on 2024-04-15 18:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_cart_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('orer_id', models.CharField(max_length=255)),
                ('update_description', models.TextField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
