# Generated by Django 5.0.1 on 2024-04-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='orer_id',
            new_name='odrer_id',
        ),
    ]
