# Generated by Django 5.0.1 on 2024-04-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_orer_id_orderupdate_odrer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='odrer_id',
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
