# Generated by Django 5.0.1 on 2024-04-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_coupon_alter_product_color_alter_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='uuid',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='colorvariant',
            old_name='uuid',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='uuid',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='uuid',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='uuid',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='sizevariant',
            old_name='uuid',
            new_name='uid',
        ),
    ]
